In [7]:
import pandas as pd
import numpy as np

# Load your dataset
data = pd.read_csv('test_main.csv')
#print(data)

years = data['Year'].unique()
companies = data['Company'].unique()
ratings = ['-2', '-1', '0', '1', '2']

# Initialize the 3D array with zeros
three_d_array = np.zeros((len(years), len(companies), len(ratings)))

# Fill the 3D array with data
for i, year in enumerate(years):
    for j, company in enumerate(companies):
        for k, rating in enumerate(ratings):
            subset = data[(data['Year'] == year) & (data['Company'] == company)]
            if not subset.empty:
                count = subset[rating].values[0]
                three_d_array[i, j, k] = count

# Check the shape of the 3D array
print(three_d_array.shape)
print(three_d_array)

(3, 3, 5)
[[[ 8. 16. 16.  9.  1.]
  [24. 34. 21. 14.  1.]
  [17.  9.  5. 14. nan]]

 [[ 8. 16. 11.  1.  2.]
  [40. 34.  8.  9.  3.]
  [12.  8. nan nan nan]]

 [[18. 25. 14.  2.  1.]
  [32. 16. 12.  6. nan]
  [10.  8.  6. nan nan]]]


In [9]:
print(three_d_array[1, 1])

[40. 34.  8.  9.  3.]


In [1]:
Year = input(print("Year? "))
Company = input(print("Company? "))

def func1():

    Year = input(print("Year? "))
    Company = input(print("Company? "))

    data_out = three_d_array[Year, Company]
    print(data_out)

func()

Year? 
